### ISSUE TITLE
Panic: Unaligned 64 bit operation on 32 bit arm

### ISSUE THREAD

**Issue by gberl002** [openziti/channel#93]
starting up an edge router throws this panic due to unaligned values in `heartbeater` struct

```
panic: unaligned 64-bit atomic operation

goroutine 118 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x45a8354)
        runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/openziti/channel/v2.(*heartbeater).Tx(0x45a8330, 0x4586080, {0x21a28b4, 0x4ac4240})
        github.com/openziti/channel/v2@v2.0.27/heartbeater.go:82 +0x1b8
github.com/openziti/channel/v2.(*channelImpl).txer(0x4ac4240)
        github.com/openziti/channel/v2@v2.0.27/impl.go:422 +0x984
created by github.com/openziti/channel/v2.(*channelImpl).startMultiplex
        github.com/openziti/channel/v2@v2.0.27/impl.go:287 +0x128
```

**Comment by gberl002** [comment]
PR merged, this didn't close automatically for some reason
